[package]
name = "ncollide-cpp"
version = "0.1.0"
authors = ["Toki Migimatsu <toki.migimatsu@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.17"
ncollide3d = "0.18"
ncollide2d = "0.18"

[lib]
crate-type = ["cdylib"]
