---
planner:
  domain: domain.pddl
  problem: problem.pddl
  depth: 5

optimizer:
  engine: ipopt
  ipopt:
    derivative_test: false
    use_hessian: false
    max_cpu_time: 600
    max_iter: 10000
    tol: 1e-2
    acceptable_tol: 1e-1
    acceptable_iter: 10
    print_level: 0 #7

world:
  objects:
    - name: wall
      T_to_parent:
        pos: [0.5, 0., 0.]
        ori: {w: 1., x: 0., y: 0., z: 0.}
      graphics:
        - geometry:
            type: box
            scale: [2., 1., 1.]
          material:
            rgba: [1., 1., 1., 0.]
          T_to_parent:
            pos: [0., -1., 0.]
            ori: {w: 1., x: 0., y: 0., z: 0.}
        - geometry:
            type: box
            scale: [2., 1., 1.]
          material:
            rgba: [1., 1., 1., 0.]
          T_to_parent:
            pos: [0., 1., 0.]
            ori: {w: 1., x: 0., y: 0., z: 0.}
        - geometry:
            type: box
            scale: [2., 1., 1.]
          material:
            rgba: [1., 1., 1., 0.]
          T_to_parent:
            pos: [-1.3, 0., 0.]
            ori: {w: 1., x: 0., y: 0., z: 0.}
        - geometry:
            type: box
            scale: [1., 1., 1.]
          material:
            rgba: [1., 1., 1., 0.]
          T_to_parent:
            pos: [1., 0., 0.]
            ori: {w: 1., x: 0., y: 0., z: 0.}
    - name: table
      graphics:
        - geometry:
            type: box
            scale: [2., 1., 0.5]
          material:
            rgba: [1., 1., 1., 0.5]
      T_to_parent:
        pos: [0.5, 0., -0.25]
        ori: {w: 1., x: 0., y: 0., z: 0.}
    - name: shelf
      T_to_parent:
        pos: [0.35, -0.35, 0.05]
        ori: {w: 1., x: 0., y: 0., z: 0.}
      graphics:
        - geometry:
            type: box
            scale: [0.3, 0.3, 0.1]
    - name: box
      T_to_parent:
        # pos: [0.9, 0., 0.025]
        pos: [0.4, 0., 0.275]
        ori: {w: 1., x: 0., y: 0., z: 0.}
      graphics:
        - geometry:
            type: box
            scale: [0.05, 0.05, 0.05]
    - name: hook
      T_to_parent:
        # pos: [0.9, 0.3, 0.005]
        pos: [0.4, 0.3, 0.255]
        ori: {w: 1., x: 0., y: 0., z: 0.}
      graphics:
        - geometry:
            type: capsule
            length: 0.25
            radius: 0.01
          T_to_parent:
            pos: [-0.09, 0.05, 0.]
            ori: {w: 0.7071, x: 0., y: 0., z: 0.7071}
        - geometry:
            type: capsule
            length: 0.1
            radius: 0.01
          T_to_parent:
            pos: [0.035, 0., 0.]
            ori: {w: 1., x: 0., y: 0., z: 0.}
    - name: ee
      T_to_parent:
        pos: [0., 0., 0.]
        ori: {w: 1., x: 0., y: 0., z: 0.}
      graphics:
        - geometry:
            type: capsule
            length: 0.1
            radius: 0.05
          material:
            rgba: [1., 1., 1., 0.2]
          T_to_parent:
            pos: [0., 0., 0.14]
            ori: {w: 0.7071, x: 0.7071, y: 0., z: 0.}
        - geometry:
            type: capsule
            length: 0.08
            radius: 0.02
          material:
            rgba: [1., 1., 1., 0.2]
          T_to_parent:
            pos: [0., 0.05, 0.05]
            ori: {w: 0.7071, x: 0.7071, y: 0., z: 0.}
        - geometry:
            type: capsule
            length: 0.08
            radius: 0.02
          material:
            rgba: [1., 1., 1., 0.2]
          T_to_parent:
            pos: [0., -0.05, 0.05]
            ori: {w: 0.7071, x: 0.7071, y: 0., z: 0.}

robot:
  urdf: ../resources/franka_panda/franka_panda.urdf
  q_home: [0., -0.5235987756, 0., -2.617993878, 0., 2.0943951024, 0.]
  ee_offset: [0., 0., 0.247]
---
