planner:
  domain: domain.pddl
  problem: problem.pddl

optimizer:
  engine: ipopt
  ipopt:
    derivative_test: false
    use_hessian: false
    max_cpu_time: 600
    max_iter: 10000
    tol: 1e-3
    acceptable_tol: 1e-2
    acceptable_iter: 10
    print_level: 0 #7

world:
  objects:
    - name: table
      T_to_parent:
        pos: [0., -0.5, 0.2]
        # pos: [0., -0.5, 0.]
        ori: {w: 1., x: 0., y: 0., z: 0.}
      graphics:
        - geometry:
            type: box
            scale: [1., 0.8, 0.25]
            # scale: [1., 0.8, 0.65]
          material:
            rgba: [1., 1., 1., 0.5]
    - name: shelf
      T_to_parent:
        pos: [0.3, -0.5, 0.4]
        ori: {w: 1., x: 0., y: 0., z: 0.}
      graphics:
        - geometry:
            type: box
            scale: [0.2, 0.2, 0.02]
    - name: far_shelf
      T_to_parent:
        pos: [-1., -0.5, 0.4]
        ori: {w: 1., x: 0., y: 0., z: 0.}
      graphics:
        - geometry:
            type: box
            scale: [0.4, 0.2, 0.02]
    - name: box
      T_to_parent:
        pos: [0., -0.5, 0.35]
        ori: {w: 1., x: 0., y: 0., z: 0.}
      graphics:
        - geometry:
            type: box
            scale: [0.05, 0.05, 0.05]
            # type: sphere
            # radius: 0.025
    - name: hook
      T_to_parent:
        pos: [0.2, -0.5, 0.335]
        ori: {w: 1., x: 0., y: 0., z: 0.}
      graphics:
        - geometry:
            type: capsule
            length: 0.2
            radius: 0.01
          T_to_parent:
            pos: [0.0317, -0.0183, 0.]
            ori: {w: 0.7071, x: 0., y: 0., z: 0.7071}
        - geometry:
            type: capsule
            length: 0.1
            radius: 0.01
          T_to_parent:
            pos: [-0.0693, 0.0327, 0.]
            ori: {w: 1., x: 0., y: 0., z: 0.}

robot:
  urdf: ../resources/kuka_iiwa/kuka_iiwa.urdf
  q_home: [1.57079632679, -0.52359877559, 0., 1.0471975512, 0., -1.57079632679, 0.]
  ee_offset: [0., 0., 0.06]

# optimizer:

